// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRsl4oirpbDHncfCvXJggSxTT1zBCKkQ',
    appId: '1:77045814771:android:ff635f2c2734ed81526e86',
    messagingSenderId: '77045814771',
    projectId: 'my-g-social',
    storageBucket: 'my-g-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ic-Sn1Eggof-3IUL33RGm_XC_BJPJ-Q',
    appId: '1:77045814771:ios:a2003debfa1de1eb526e86',
    messagingSenderId: '77045814771',
    projectId: 'my-g-social',
    storageBucket: 'my-g-social.appspot.com',
    iosClientId: '77045814771-le2bqevtmrd73see06ibkgitdiokp8uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsoci',
  );
}
